name: dinamics_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  http: ^0.13.3  # Para manejar las solicitudes HTTP
  flutter_secure_storage: ^8.0.0
  mysql1: ^0.19.0  # O la versión más reciente disponible
  connectivity_plus: ^5.0.2  # Añadimos esta línea

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
